[metadata]
name = lbpextract
version = 0.2.2
author = hayj
description = A tool to convert La Banque Postale's account documents (PDFs) into CSV files.
url = https://github.com/hayj/LBPExtract
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
packages = find:
python_requires = >=3.10
install_requires =
    pandas
    systools
    PyMuPDF>=1.24.0,<2
    tqdm

[options.entry_points]
console_scripts =
    lbpextract = lbpextract.parser:main
